[book]
authors = ["sylide"]
language = "ja"
src = "src"
title = "mincaml-rs Documentation"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.xgettext]
optional = true
pot-file = "messages.pot"
granularity = 0

[preprocessor.toc]
renderer = ["html"]

[output.pandoc]
optional = true
disabled = true

[output.pandoc.profile.pdf]
output-file = "mincaml-rs-doc.pdf"
pdf-engine = "typst"

[output.html]

[output.linkcheck]
optional = true
follow-web-links = false
